
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
